import type {
  Agent,
  ApprovalDecision,
  Transaction,
  User,
  Vendor,
} from "./types";

export const mockUsers: User[] = [
  {
    userId: "user_admin",
    clientId: "client_acme",
    email: "admin@custos.local",
    fullName: "Admin User",
    role: "admin",
    status: "active",
    phoneNumber: null,
    jobTitle: "Platform Admin",
    timezone: "America/New_York",
    defaultCurrency: "USD",
    defaultPaymentMethod: "ach",
    notificationEmailEnabled: true,
    notificationSmsEnabled: false,
    approvalNotificationsEnabled: true,
    theme: "light",
    preferences: {},
    metadata: {},
    createdAt: "2026-01-01T09:00:00Z",
    updatedAt: "2026-03-21T09:00:00Z",
  },
  {
    userId: "user_acme_owner",
    clientId: "client_acme",
    email: "ops@acmerobotics.com",
    fullName: "Avery Stone",
    role: "owner",
    status: "active",
    phoneNumber: null,
    jobTitle: "COO",
    timezone: "America/New_York",
    defaultCurrency: "USD",
    defaultPaymentMethod: "ach",
    notificationEmailEnabled: true,
    notificationSmsEnabled: false,
    approvalNotificationsEnabled: true,
    theme: "light",
    preferences: {},
    metadata: { companyName: "Acme Robotics", companyStatus: "active" },
    createdAt: "2026-01-05T10:00:00Z",
    updatedAt: "2026-03-21T10:00:00Z",
  },
  {
    userId: "user_orbit_owner",
    clientId: "client_orbit",
    email: "finance@orbithealth.com",
    fullName: "Morgan Lee",
    role: "finance",
    status: "active",
    phoneNumber: null,
    jobTitle: "Finance Director",
    timezone: "America/New_York",
    defaultCurrency: "USD",
    defaultPaymentMethod: "ach",
    notificationEmailEnabled: true,
    notificationSmsEnabled: false,
    approvalNotificationsEnabled: true,
    theme: "light",
    preferences: {},
    metadata: { companyName: "Orbit Health", companyStatus: "under_review" },
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-03-21T09:00:00Z",
  },
  {
    userId: "user_summit_owner",
    clientId: "client_summit",
    email: "ops@summitlegal.com",
    fullName: "Jordan Park",
    role: "owner",
    status: "active",
    phoneNumber: null,
    jobTitle: "Managing Partner",
    timezone: "America/New_York",
    defaultCurrency: "USD",
    defaultPaymentMethod: "card",
    notificationEmailEnabled: true,
    notificationSmsEnabled: false,
    approvalNotificationsEnabled: true,
    theme: "light",
    preferences: {},
    metadata: { companyName: "Summit Legal", companyStatus: "active" },
    createdAt: "2026-02-18T09:00:00Z",
    updatedAt: "2026-03-21T09:00:00Z",
  },
];

export const mockVendors: Vendor[] = [
  {
    vendorId: "vendor_stripe",
    clientId: "client_acme",
    vendorName: "Stripe",
    vendorLegalName: "Stripe, Inc.",
    vendorStatus: "active",
    contact: { name: "Billing", email: "billing@stripe.com" },
    paymentMethodsSupported: ["ach", "wire"],
    preferredPaymentMethod: "ach",
    encryptedPaymentRefId: "ref_vendor_stripe",
    defaultCurrency: "USD",
    vendorCategory: "software",
    rules: {
      maxAmountPerTransaction: 10000,
      paymentFrequency: "monthly",
      preferredPaymentMethods: ["ach"],
      requiresHumanApprovalAbove: 5000,
    },
    notes: null,
    tags: ["payments"],
    metadata: {},
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
  },
  {
    vendorId: "vendor_aws",
    clientId: "client_acme",
    vendorName: "AWS",
    vendorLegalName: "Amazon Web Services, Inc.",
    vendorStatus: "active",
    contact: { name: "Cloud Billing", email: "aws-billing@amazon.com" },
    paymentMethodsSupported: ["card", "ach"],
    preferredPaymentMethod: "card",
    encryptedPaymentRefId: "ref_vendor_aws",
    defaultCurrency: "USD",
    vendorCategory: "cloud",
    rules: {
      maxAmountPerTransaction: 12000,
      paymentFrequency: "monthly",
      preferredPaymentMethods: ["card", "ach"],
      requiresHumanApprovalAbove: 3000,
    },
    notes: null,
    tags: ["cloud"],
    metadata: {},
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
  },
  {
    vendorId: "vendor_lab",
    clientId: "client_orbit",
    vendorName: "LabSupply Co.",
    vendorLegalName: "LabSupply Co.",
    vendorStatus: "active",
    contact: { name: "Sales", email: "orders@labsupply.example" },
    paymentMethodsSupported: ["ach", "card"],
    preferredPaymentMethod: "ach",
    encryptedPaymentRefId: "ref_vendor_lab",
    defaultCurrency: "USD",
    vendorCategory: "supplies",
    rules: {
      maxAmountPerTransaction: 6000,
      paymentFrequency: "one_time",
      preferredPaymentMethods: ["ach"],
      requiresHumanApprovalAbove: 1500,
    },
    notes: null,
    tags: ["lab"],
    metadata: {},
    createdAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
  },
  {
    vendorId: "vendor_lexis",
    clientId: "client_summit",
    vendorName: "LexisNexis",
    vendorLegalName: "LexisNexis",
    vendorStatus: "active",
    contact: { name: "Support", email: "support@lexisnexis.com" },
    paymentMethodsSupported: ["card"],
    preferredPaymentMethod: "card",
    encryptedPaymentRefId: "ref_vendor_lexis",
    defaultCurrency: "USD",
    vendorCategory: "software",
    rules: {
      maxAmountPerTransaction: 2500,
      paymentFrequency: "monthly",
      preferredPaymentMethods: ["card"],
      requiresHumanApprovalAbove: 1000,
    },
    notes: null,
    tags: ["research"],
    metadata: {},
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
  },
];

export const mockAgents: Agent[] = [
  {
    agentId: "agt_acme_ap",
    clientId: "client_acme",
    agentName: "Accounts Payable Agent",
    agentType: "invoice",
    agentStatus: "active",
    apiKeyId: "key_1",
    apiKeyPrefix: "cust_ap_",
    monthlyAllowance: 120000,
    approvalThreshold: 5000,
    maxTransactionAmount: 15000,
    currency: "USD",
    vendorAllowlist: ["vendor_stripe", "vendor_aws"],
    vendorDenylist: ["vendor_unverified"],
    allowedPaymentMethods: ["ach", "wire"],
    description: "Processes recurring vendor invoices for finance ops.",
    createdByUserId: "user_acme_owner",
    settings: {},
    metadata: { riskLevel: "medium", lastActiveAt: "2026-03-20T14:15:00Z" },
    createdAt: "2026-01-05T10:00:00Z",
    updatedAt: "2026-03-20T14:15:00Z",
  },
  {
    agentId: "agt_acme_cloud",
    clientId: "client_acme",
    agentName: "Cloud Spend Agent",
    agentType: "infrastructure",
    agentStatus: "paused",
    apiKeyId: "key_2",
    apiKeyPrefix: "cust_cld_",
    monthlyAllowance: 80000,
    approvalThreshold: 2500,
    maxTransactionAmount: 10000,
    currency: "USD",
    vendorAllowlist: ["vendor_aws"],
    vendorDenylist: ["vendor_unverified"],
    allowedPaymentMethods: ["card", "ach"],
    description: "Handles cloud usage and infra renewals.",
    createdByUserId: "user_acme_owner",
    settings: {},
    metadata: { riskLevel: "high", lastActiveAt: "2026-03-18T09:30:00Z" },
    createdAt: "2026-02-01T09:00:00Z",
    updatedAt: "2026-03-18T09:30:00Z",
  },
  {
    agentId: "agt_orbit_ops",
    clientId: "client_orbit",
    agentName: "Operations Purchasing Agent",
    agentType: "ops",
    agentStatus: "active",
    apiKeyId: "key_3",
    apiKeyPrefix: "cust_ops_",
    monthlyAllowance: 45000,
    approvalThreshold: 1500,
    maxTransactionAmount: 6000,
    currency: "USD",
    vendorAllowlist: ["vendor_lab"],
    vendorDenylist: [],
    allowedPaymentMethods: ["ach", "card"],
    description: "Procures operations and lab supplies.",
    createdByUserId: "user_orbit_owner",
    settings: {},
    metadata: { riskLevel: "medium", lastActiveAt: "2026-03-21T11:20:00Z" },
    createdAt: "2026-02-12T11:00:00Z",
    updatedAt: "2026-03-21T11:20:00Z",
  },
  {
    agentId: "agt_summit_cases",
    clientId: "client_summit",
    agentName: "Case Research Agent",
    agentType: "research",
    agentStatus: "active",
    apiKeyId: "key_4",
    apiKeyPrefix: "cust_res_",
    monthlyAllowance: 20000,
    approvalThreshold: 750,
    maxTransactionAmount: 2500,
    currency: "USD",
    vendorAllowlist: ["vendor_lexis"],
    vendorDenylist: ["vendor_crypto"],
    allowedPaymentMethods: ["card"],
    description: "Supports legal research and filing costs.",
    createdByUserId: "user_summit_owner",
    settings: {},
    metadata: { riskLevel: "low", lastActiveAt: "2026-03-21T13:45:00Z" },
    createdAt: "2026-02-20T08:30:00Z",
    updatedAt: "2026-03-21T13:45:00Z",
  },
];

export const mockTransactions: Transaction[] = [
  {
    transactionId: "txn_1001",
    clientId: "client_acme",
    vendorId: "vendor_stripe",
    vendorNameSnapshot: "Stripe",
    agentId: "agt_acme_ap",
    requestedByUserId: null,
    transactionType: "invoice",
    amount: 4200,
    currency: "USD",
    paymentMethod: "ach",
    paymentStatus: "scheduled",
    approvalStatus: "auto_approved",
    ruleEvaluationResult: "approved_by_rules",
    humanApprovalRequired: false,
    humanApprovalReceived: false,
    humanApprovedByUserId: null,
    humanApprovedAt: null,
    requestedPaymentDatetime: "2026-03-25T09:00:00Z",
    scheduledPaymentDatetime: "2026-03-25T09:00:00Z",
    paidAt: null,
    invoiceFilePath: "invoices/acme/stripe-mar.pdf",
    description: "March billing for payments infrastructure.",
    externalPaymentId: null,
    encryptedPaymentRefId: "ref_1001",
    failureReason: null,
    complianceFlags: [],
    metadata: {
      manualReviewStatus: "verified",
      manuallyVerifiedByUserId: "user_admin",
      manuallyVerifiedAt: "2026-03-19T10:02:00Z",
    },
    createdAt: "2026-03-19T10:00:00Z",
    updatedAt: "2026-03-19T10:03:00Z",
    auditTrail: [
      {
        eventId: "evt_1001_1",
        eventType: "created",
        eventTimestamp: "2026-03-19T10:00:00Z",
        actorType: "agent",
        actorId: "agt_acme_ap",
        details: {},
      },
      {
        eventId: "evt_1001_2",
        eventType: "rules_checked",
        eventTimestamp: "2026-03-19T10:01:00Z",
        actorType: "system",
        actorId: null,
        details: { result: "approved_by_rules" },
      },
    ],
  },
  {
    transactionId: "txn_1002",
    clientId: "client_acme",
    vendorId: "vendor_aws",
    vendorNameSnapshot: "AWS",
    agentId: "agt_acme_cloud",
    requestedByUserId: null,
    transactionType: "card_payment",
    amount: 7200,
    currency: "USD",
    paymentMethod: "card",
    paymentStatus: "pending",
    approvalStatus: "pending_human_approval",
    ruleEvaluationResult: "needs_review",
    humanApprovalRequired: true,
    humanApprovalReceived: false,
    humanApprovedByUserId: null,
    humanApprovedAt: null,
    requestedPaymentDatetime: "2026-03-22T12:00:00Z",
    scheduledPaymentDatetime: null,
    paidAt: null,
    invoiceFilePath: "invoices/acme/aws-renewal.pdf",
    description: "Reserved instance renewal.",
    externalPaymentId: null,
    encryptedPaymentRefId: "ref_1002",
    failureReason: null,
    complianceFlags: ["approval_threshold_exceeded"],
    metadata: {
      manualReviewStatus: "pending",
      manuallyVerifiedByUserId: null,
      manuallyVerifiedAt: null,
    },
    createdAt: "2026-03-20T16:40:00Z",
    updatedAt: "2026-03-20T16:45:00Z",
    auditTrail: [
      {
        eventId: "evt_1002_1",
        eventType: "created",
        eventTimestamp: "2026-03-20T16:40:00Z",
        actorType: "agent",
        actorId: "agt_acme_cloud",
        details: {},
      },
      {
        eventId: "evt_1002_2",
        eventType: "sent_for_approval",
        eventTimestamp: "2026-03-20T16:45:00Z",
        actorType: "system",
        actorId: null,
        details: { reason: "approval_threshold_exceeded" },
      },
    ],
  },
  {
    transactionId: "txn_2001",
    clientId: "client_orbit",
    vendorId: "vendor_lab",
    vendorNameSnapshot: "LabSupply Co.",
    agentId: "agt_orbit_ops",
    requestedByUserId: null,
    transactionType: "ach",
    amount: 1900,
    currency: "USD",
    paymentMethod: "ach",
    paymentStatus: "processing",
    approvalStatus: "human_approved",
    ruleEvaluationResult: "needs_review",
    humanApprovalRequired: true,
    humanApprovalReceived: true,
    humanApprovedByUserId: "user_admin",
    humanApprovedAt: "2026-03-21T12:05:00Z",
    requestedPaymentDatetime: "2026-03-21T13:00:00Z",
    scheduledPaymentDatetime: "2026-03-21T13:00:00Z",
    paidAt: null,
    invoiceFilePath: "invoices/orbit/lab-order.pdf",
    description: "Emergency lab consumables.",
    externalPaymentId: "pay_2001",
    encryptedPaymentRefId: "ref_2001",
    failureReason: null,
    complianceFlags: [],
    metadata: {
      manualReviewStatus: "verified",
      manuallyVerifiedByUserId: "user_admin",
      manuallyVerifiedAt: "2026-03-21T12:00:00Z",
    },
    createdAt: "2026-03-21T11:30:00Z",
    updatedAt: "2026-03-21T12:05:00Z",
    auditTrail: [
      {
        eventId: "evt_2001_1",
        eventType: "created",
        eventTimestamp: "2026-03-21T11:30:00Z",
        actorType: "agent",
        actorId: "agt_orbit_ops",
        details: {},
      },
      {
        eventId: "evt_2001_2",
        eventType: "approved",
        eventTimestamp: "2026-03-21T12:05:00Z",
        actorType: "user",
        actorId: "user_admin",
        details: {},
      },
    ],
  },
  {
    transactionId: "txn_3001",
    clientId: "client_summit",
    vendorId: "vendor_lexis",
    vendorNameSnapshot: "LexisNexis",
    agentId: "agt_summit_cases",
    requestedByUserId: null,
    transactionType: "card_payment",
    amount: 680,
    currency: "USD",
    paymentMethod: "card",
    paymentStatus: "paid",
    approvalStatus: "auto_approved",
    ruleEvaluationResult: "approved_by_rules",
    humanApprovalRequired: false,
    humanApprovalReceived: false,
    humanApprovedByUserId: null,
    humanApprovedAt: null,
    requestedPaymentDatetime: "2026-03-17T15:00:00Z",
    scheduledPaymentDatetime: "2026-03-17T15:00:00Z",
    paidAt: "2026-03-17T15:10:00Z",
    invoiceFilePath: null,
    description: "Research database subscription top-up.",
    externalPaymentId: "pay_3001",
    encryptedPaymentRefId: "ref_3001",
    failureReason: null,
    complianceFlags: [],
    metadata: {
      manualReviewStatus: "verified",
      manuallyVerifiedByUserId: "user_admin",
      manuallyVerifiedAt: "2026-03-17T14:50:00Z",
    },
    createdAt: "2026-03-17T14:40:00Z",
    updatedAt: "2026-03-17T15:10:00Z",
    auditTrail: [
      {
        eventId: "evt_3001_1",
        eventType: "paid",
        eventTimestamp: "2026-03-17T15:10:00Z",
        actorType: "system",
        actorId: null,
        details: {},
      },
    ],
  },
];

export const mockApprovalDecisions: ApprovalDecision[] = [
  {
    approvalDecisionId: "apd_2001",
    transactionId: "txn_2001",
    approvedByUserId: "user_admin",
    decision: "approved",
    reason: "Emergency purchase approved",
    createdAt: "2026-03-21T12:05:00Z",
  },
];
